# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "041d4df59e804374540c50ade9268ac8"
name = "Lighthouse Scanner"
handle = "google-lighthouse-scanner"
application_url = "https://committee-violent-probability-pleasure.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-dev-store-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://committee-violent-probability-pleasure.trycloudflare.com/auth/callback",
  "https://committee-violent-probability-pleasure.trycloudflare.com/auth/shopify/callback",
  "https://committee-violent-probability-pleasure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
