name: CI Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add other steps for building/testing your app if needed
